### ISSUE TITLE
Employer/Workplace considerations?

### ISSUE THREAD

**Issue by morthSith** [hlaueriksson/ama#1]
## As an experienced Software developer, how would your top 5 list of important considerations look like when choosing an employer/workplace?

Here are surveys done 2015 and 2016 by academic work(swedish company), on newly graduates/academics at the start of their careers. 

For more info see: 
2015: https://www.academicwork.se/ypai2015
2016: https://www.academicwork.se/ypai2016

Results can be seen below:

2016:
**1. Nice work colleagues and good atmosphere
2. Good development opportunities 
3. Good salary and benefits 
4. Good boss / Leadership 
5. Good working environment
6. Challenging tasks
7. Secure employment / Safe working conditions
8. Geographical location / proximity to home
9. Personal responsibility / own decisions 
10. Flexibility / Flexible working**

2015:
**1. Good boss / Leadership 
2. Nice colleagues / good atmosphere  
3. Good development opportunities  
4. Good salary and benefits
5. Good working environment
6. Secure employment / Safe working conditions  
7. Personal responsibility / own decisions   
8. Competence and professionalism
9. Clear goals and roles
10. Challenging tasks  
11. Transparency
12. A respectful environment  
13. An active social responsibility (CSR)**

**Comment by hlaueriksson** [comment]
This is a really good question! All those things are important to me.

This is how I feel right now:

**1. Nice colleagues / good atmosphere
2. Competence and professionalism
3. Challenging tasks
4. Good salary and benefits
5. Good working environment**

_(Next week I may have another opinion)_
