### ISSUE TITLE
How did you develop codeofconduct.io ?

### ISSUE THREAD

**Issue by Digvijay** [hlaueriksson/ama#2]
Is it a blogging platform or just a text/markdown to static html converter?

**Comment by hlaueriksson** [comment]
> Every developer should have a blog

as Scott Hanselman puts it.

It took a long time for me to follow that advice. But one year ago I created my own blog. I write about programming and the things I have learned.

It is a [Jekyll](http://jekyllrb.com) blog hosted on [GitHub Pages](https://pages.github.com). So the content is just markdown files that are transformed into static html.

I have [installed](http://conductofcode.io/post/setting-up-jekyll-on-windows/) and [configured](http://conductofcode.io/post/blogging-with-jekyll-on-github-pages/) Jekyll on my local machine. I write the posts in a text editor. I run the `jekyll s` command in a console to be able to view the blog on `http://localhost:4000`. When I am ready to publish a new post I push the commits to the `gh-pages` branch on GitHub. Then GitHub Pages generates the site and everyone can read the new post on [http://conductofcode.io](http://conductofcode.io)

You can have a look at all the files that makes up the blog at [https://github.com/hlaueriksson/conductofcode.io](https://github.com/hlaueriksson/conductofcode.io)
